/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'travism' at '1/28/16 2:08 PM' with Gradle 2.9
 *
 * @author travism, @date 1/28/16 2:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
